import { chromium, type Locator, type Page } from "playwright";
import { lookup } from "node:dns/promises";
import { normalizeLinkedInUrl } from "./normalize";

export type ReactionPerson = { profileUrl:string; name:string; headline?:string; jobTitle?:string; company?:string; type:"REACTION"; reactionType?:string };
const clean=(v:string|null|undefined)=>(v??"").replace(/\s+/g," ").trim();
const profile=(v:string)=>{const u=normalizeLinkedInUrl(v);return /linkedin\.com\/in\//i.test(u)?u:"";};
const generic=(v:string)=>/^(like|comment|repost|send|follow|most relevant|most recent|reactions?|likes?|people who reacted|close|cancel|done|back|next|previous|see all|show more|load more|connections?|grow your network|my network|notifications?|messaging|jobs|home|search|me|for business|celebrate|support|love|insightful|funny)$/i.test(clean(v))||clean(v).length<2;
async function connectPage():Promise<{browser:any;page:Page}>{const configured=new URL(process.env.LINKEDIN_CDP_URL??"http://host.docker.internal:9222");let host=configured.hostname;if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(host)&&host!=="localhost"){const a=await lookup(host,{all:true});const v4=a.find(x=>x.family===4);if(!v4)throw new Error(`Could not resolve ${host} to IPv4.`);host=v4.address;}const endpoint=`http://${host}:${configured.port||"9222"}`;const r=await fetch(`${endpoint}/json/version`,{headers:{Host:host}});if(!r.ok)throw new Error(`Chrome CDP endpoint returned HTTP ${r.status}.`);const v=await r.json() as {Browser?:string;webSocketDebuggerUrl?:string};if(v.Browser)console.log(`Chrome CDP browser: ${v.Browser}`);if(!v.webSocketDebuggerUrl)throw new Error("Chrome CDP did not return a browser WebSocket endpoint.");const browser=await chromium.connectOverCDP(v.webSocketDebuggerUrl,{timeout:90000});const context=browser.contexts()[0];if(!context)throw new Error("Chrome CDP connected, but no browser context is available.");return {browser,page:await context.newPage()};}
async function findPostRoot(page:Page,postUrl:string):Promise<Locator|null>{const id=postUrl.match(/(?:ugcPost-|activity-)(\d+)/i)?.[1]??"";if(id){const direct=page.locator(`[data-urn*="${id}"],[data-id*="${id}"]`);const n=Math.min(await direct.count().catch(()=>0),20);for(let i=0;i<n;i++){const node=direct.nth(i);if(!(await node.isVisible().catch(()=>false)))continue;const article=node.locator("xpath=ancestor::article[1]");if(await article.count().catch(()=>0))return article;return node;}}return page.locator("article").filter({hasText:/\breactions?\b|\blikes?\b/i}).first();}
async function findTrigger(page:Page,postUrl:string):Promise<Locator|null>{const root=await findPostRoot(page,postUrl);if(!root||!(await root.count().catch(()=>0)))return null;const controls=root.locator("button,[role='button'],a,[tabindex='0'],span");const n=Math.min(await controls.count().catch(()=>0),700);const diagnostics:string[]=[];for(let i=0;i<n;i++){const c=controls.nth(i);if(!(await c.isVisible().catch(()=>false)))continue;const text=clean(await c.innerText().catch(()=>""));const aria=clean(await c.getAttribute("aria-label").catch(()=>""));const title=clean(await c.getAttribute("title").catch(()=>""));const data=clean(await c.getAttribute("data-view-name").catch(()=>""));const combined=`${text} ${aria} ${title} ${data}`;if(/reaction|like/i.test(combined)&&diagnostics.length<30)diagnostics.push(combined.slice(0,140));if(/\b\d[\d,.]*\s+(?:reactions?|likes?)\b/i.test(`${text} ${aria} ${title}`)){const click=c.locator("xpath=ancestor-or-self::*[self::button or @role='button' or self::a][1]");return await click.count().catch(()=>0)?click.first():c;}if(/reaction|like/i.test(combined)&&!/reply|follow|my network|notification|messaging/i.test(combined)){const click=c.locator("xpath=ancestor-or-self::*[self::button or @role='button' or self::a][1]");return await click.count().catch(()=>0)?click.first():c;}}if(diagnostics.length)console.log(`Reaction control candidates: ${diagnostics.join(" | ")}`);return null;}
function profileAnchors(page:Page|Locator){return page.locator('a[href*="/in/"],a[data-profile-url],a[data-test-profile-url]');}
async function snapshotProfiles(page:Page){const seen=new Set<string>();const anchors=profileAnchors(page);const n=Math.min(await anchors.count().catch(()=>0),2500);for(let i=0;i<n;i++){const a=anchors.nth(i);const href=profile((await a.getAttribute("href").catch(()=>""))||(await a.getAttribute("data-profile-url").catch(()=>""))||(await a.getAttribute("data-test-profile-url").catch(()=>""))||"");if(href)seen.add(href.toLowerCase());}return seen;}
function reactionSurface(page:Page){return page.locator('[role="dialog"],[role="listbox"],[role="list"],[role="tabpanel"],.artdeco-modal,.artdeco-popover,[data-test-modal],[data-test-dialog],[data-test-popover]').filter({hasText:/people who reacted|\breactions?\b|\blikes?/i}).last();}
async function waitReactionSurface(page:Page):Promise<Locator|null>{for(let i=0;i<10;i++){const s=reactionSurface(page);if(await s.count().catch(()=>0))return s;await page.waitForTimeout(300);}return null;}
async function freshProfiles(page:Page,before:Set<string>,max:number){const out:ReactionPerson[]=[];const anchors=profileAnchors(page);const n=Math.min(await anchors.count().catch(()=>0),2500);const seen=new Set<string>(before);for(let i=0;i<n&&out.length<max;i++){const a=anchors.nth(i);if(!(await a.isVisible().catch(()=>false)))continue;const href=profile((await a.getAttribute("href").catch(()=>""))||(await a.getAttribute("data-profile-url").catch(()=>""))||(await a.getAttribute("data-test-profile-url").catch(()=>""))||"");const name=clean((await a.textContent().catch(()=>""))||(await a.getAttribute("aria-label").catch(()=>"")));if(!href||!name||generic(name)||seen.has(href.toLowerCase()))continue;const context=await a.locator("xpath=ancestor::*[self::li or self::div][1]").innerText().catch(()=>"");if(/comment|reply/i.test(context)&&!/reaction|react|people who/i.test(context))continue;seen.add(href.toLowerCase());out.push({profileUrl:href,name,type:"REACTION",reactionType:"UNKNOWN"});}return out;}
async function extractSurface(surface:Locator,seen:Set<string>,max:number){const out:ReactionPerson[]=[];const anchors=profileAnchors(surface);const n=Math.min(await anchors.count().catch(()=>0),1000);for(let i=0;i<n&&out.length<max;i++){const a=anchors.nth(i);if(!(await a.isVisible().catch(()=>false)))continue;const href=profile((await a.getAttribute("href").catch(()=>""))||(await a.getAttribute("data-profile-url").catch(()=>""))||(await a.getAttribute("data-test-profile-url").catch(()=>""))||"");const name=clean((await a.textContent().catch(()=>""))||(await a.getAttribute("aria-label").catch(()=>"")));if(!href||!name||generic(name)||seen.has(href.toLowerCase()))continue;seen.add(href.toLowerCase());out.push({profileUrl:href,name,type:"REACTION",reactionType:"UNKNOWN"});}return out;}
export async function scrapeReactions(postUrl:string,max=500):Promise<{reactions:ReactionPerson[];warnings:string[]}>{const warnings:string[]=[];const {browser,page}=await connectPage();try{await page.goto(postUrl,{waitUntil:"domcontentloaded",timeout:30000});await page.waitForTimeout(1800);const trigger=await findTrigger(page,postUrl);if(!trigger)return{reactions:[],warnings:["Could not locate the reaction interaction control inside the LinkedIn post."]};const before=await snapshotProfiles(page);console.log("Reaction interaction control found by post-scoped detection; capturing profile snapshot and clicking it.");await trigger.scrollIntoViewIfNeeded().catch(()=>{});await trigger.click({timeout:5000}).catch(async()=>trigger.click({timeout:5000,force:true}));await page.waitForTimeout(900);const reactions:ReactionPerson[]=[];const seen=new Set<string>(before);for(let round=0;round<25&&reactions.length<max;round++){const fresh=await freshProfiles(page,before,max-reactions.length);for(const item of fresh){if(!seen.has(item.profileUrl.toLowerCase())){seen.add(item.profileUrl.toLowerCase());reactions.push(item);}}const surface=await waitReactionSurface(page);if(surface){const found=await extractSurface(surface,seen,max-reactions.length);reactions.push(...found);await surface.focus().catch(()=>{});await surface.press("PageDown").catch(()=>{});}await page.waitForTimeout(450);if(!fresh.length&&!surface)break;}if(!reactions.length){warnings.push("Reaction interaction opened, but no new public LinkedIn profile URLs were exposed.");}console.log(`Reaction extraction enriched records: ${reactions.length}`);return{reactions,warnings};}finally{await page.close().catch(()=>{});await browser.close().catch(()=>{});}}
