import { chromium, type Locator, type Page } from "playwright";
import { lookup } from "node:dns/promises";
import { normalizeLinkedInUrl } from "./normalize";

export type ScrapedEngagement = { profileUrl:string; name:string; headline?:string; jobTitle?:string; company?:string; type:"COMMENT"|"REACTION"; reactionType?:string; commentText?:string; engagedAt?:Date };
export type ScrapeResult = { engagements:ScrapedEngagement[]; warnings:string[] };
const clean=(v:string|null|undefined)=>(v??"").replace(/\s+/g," ").trim();
const profile=(v:string)=>{const u=normalizeLinkedInUrl(v);return /linkedin\.com\/in\//i.test(u)?u:"";};
const generic=(v:string)=>/^(like|comment|repost|send|follow|most relevant|most recent|reactions?|likes?|people who reacted|close|cancel|done|back|next|previous|see all|show more|load more|connections?|grow your network|my network|notifications?|messaging|jobs|home|search|me|for business|celebrate|support|love|insightful|funny)$/i.test(clean(v))||clean(v).length<2;
async function connect(){const configured=new URL(process.env.LINKEDIN_CDP_URL??"http://host.docker.internal:9222");let host=configured.hostname;if(!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(host)&&host!=="localhost"){const a=await lookup(host,{all:true});const v4=a.find(x=>x.family===4);if(!v4)throw new Error(`Could not resolve ${host} to IPv4.`);host=v4.address;}const endpoint=`http://${host}:${configured.port||"9222"}`;const r=await fetch(`${endpoint}/json/version`,{headers:{Host:host}});if(!r.ok)throw new Error(`Chrome CDP endpoint returned HTTP ${r.status}.`);const v=await r.json() as {Browser?:string;webSocketDebuggerUrl?:string};console.log(`Chrome CDP browser: ${v.Browser??"unknown"}`);if(!v.webSocketDebuggerUrl)throw new Error("Chrome CDP did not return a browser WebSocket endpoint.");const browser=await chromium.connectOverCDP(v.webSocketDebuggerUrl,{timeout:90000});const context=browser.contexts()[0];if(!context)throw new Error("Chrome CDP connected, but no browser context is available.");return {browser,page:await context.newPage()};}
function postId(url:string){return url.match(/(?:ugcPost-|activity-)(\d+)/i)?.[1]??"";}
async function nearestClickable(node:Locator){const c=node.locator("xpath=ancestor-or-self::*[self::button or @role='button' or self::a][1]");return await c.count().catch(()=>0)?c.first():node;}
async function controls(page:Page,kind:"comments"|"reactions",postUrl:string){const countRe=kind==="comments"?/\b\d[\d,.]*\s+comments?\b/i:/\b\d[\d,.]*\s+(?:reactions?|likes?)\b/i;const labelRe=kind==="comments"?/comment/i:/reaction|like/i;const all=page.locator("button,[role='button'],a,[tabindex='0'],span");const n=Math.min(await all.count().catch(()=>0),1600);const hits:string[]=[];for(let i=0;i<n;i++){const x=all.nth(i);const text=clean(await x.innerText().catch(()=>""));const aria=clean(await x.getAttribute("aria-label").catch(()=>""));const title=clean(await x.getAttribute("title").catch(()=>""));const data=clean(await x.getAttribute("data-view-name").catch(()=>""));const s=`${text} ${aria} ${title} ${data}`;if(labelRe.test(s)&&hits.length<30)hits.push(s.slice(0,140));if(countRe.test(text)||countRe.test(aria)||countRe.test(title))return nearestClickable(x);}console.log(`${kind} control diagnostics: ${hits.join(" | ")||"no labelled candidates"}`);const body=clean(await page.locator("body").innerText().catch(()=>""));console.log(`${kind} body-text diagnostic: ${body.match(/.{0,70}(?:\d[\d,.]*\s+)?(?:reactions?|likes?|comments?).{0,70}/ig)?.slice(0,15).join(" || ")||"no reaction/comment count text in body"}`);return null;}
function overlayCandidates(page:Page){return page.locator('[role="dialog"],[role="listbox"],[role="list"],[role="tabpanel"],.artdeco-modal,.artdeco-popover,[data-test-modal],[data-test-dialog],[data-test-popover]');}
async function reactionSurfaceAfterClick(page:Page){for(let i=0;i<12;i++){const specific=overlayCandidates(page).filter({hasText:/people who reacted|\breactions?\b|\blikes?/i}).last();if(await specific.count().catch(()=>0))return specific;await page.waitForTimeout(300);}const overlays=overlayCandidates(page);const n=Math.min(await overlays.count().catch(()=>0),20);for(let i=n-1;i>=0;i--){const s=overlays.nth(i);if(!(await s.isVisible().catch(()=>false)))continue;const links=await s.locator('a[href*="/in/"]').count().catch(()=>0);const txt=clean(await s.innerText().catch(()=>""));if(links||/react|like|people/i.test(txt))return s;}return null;}
function commentSurface(page:Page){return overlayCandidates(page).filter({hasText:/comment|reply/i}).last();}
async function clickControl(page:Page,c:Locator,label:string){console.log(`${label} control found; clicking it.`);await c.scrollIntoViewIfNeeded().catch(()=>{});await c.click({timeout:5000}).catch(async()=>c.click({timeout:5000,force:true}));await page.waitForTimeout(1200);}
async function climbComment(anchor:Locator){let node=anchor;for(let i=0;i<10;i++){const txt=clean(await node.innerText().catch(()=>""));if(/\breply\b/i.test(txt)&&txt.length<4000)return node;const p=node.locator("xpath=..");if(!(await p.count().catch(()=>0)))break;node=p;}return null;}
async function extractComments(page:Page,max:number,postUrl:string){const c=await controls(page,"comments",postUrl);if(c)await clickControl(page,c,"Comment interaction");else console.log("Comment count control not found; scanning current comment UI only.");for(let r=0;r<12;r++){const s=commentSurface(page);if(!(await s.count().catch(()=>0)))break;const more=s.locator("button,[role='button']");const mn=Math.min(await more.count().catch(()=>0),150);let clicked=false;for(let i=0;i<mn;i++){const b=more.nth(i);if(!(await b.isVisible().catch(()=>false)))continue;const l=clean((await b.getAttribute("aria-label").catch(()=>""))||await b.innerText().catch(()=>""));if(/load more|show more|view more|previous comments|more comments/i.test(l)){await b.click().catch(()=>{});await page.waitForTimeout(500);clicked=true;break;}}if(!clicked)break;}const scope=commentSurface(page);const root=await scope.count().catch(()=>0)?scope:page.locator("main").first();const anchors=root.locator('a[href*="/in/"],a[data-profile-url],a[data-test-profile-url]');const n=Math.min(await anchors.count().catch(()=>0),Math.max(max*8,100));const out:ScrapedEngagement[]=[];const seen=new Set<string>();for(let i=0;i<n&&out.length<max;i++){const a=anchors.nth(i);if(!(await a.isVisible().catch(()=>false)))continue;const href=profile((await a.getAttribute("href").catch(()=>""))||(await a.getAttribute("data-profile-url").catch(()=>""))||(await a.getAttribute("data-test-profile-url").catch(()=>""))||"");const name=clean((await a.textContent().catch(()=>""))||(await a.getAttribute("aria-label").catch(()=>"")));if(!href||!name||generic(name)||seen.has(href.toLowerCase()))continue;const box=await climbComment(a);if(!box)continue;const txt=clean(await box.innerText().catch(()=>""));const lines=txt.split(/\n+/).map(clean).filter(Boolean);const idx=lines.findIndex(x=>x.toLowerCase()===name.toLowerCase());const body=idx>=0?lines.slice(idx+1).filter(x=>!/^(like|reply|follow|edited|see more|see less|translate)$/i.test(x)).join(" ").slice(0,5000):"";if(!body)continue;seen.add(href.toLowerCase());out.push({profileUrl:href,name,type:"COMMENT",commentText:body});}console.log(`Comment diagnostics: anchors=${n}, captured=${out.length}`);return out;}
async function extractReactions(page:Page,max:number,postUrl:string,warnings:string[]){const c=await controls(page,"reactions",postUrl);if(!c){warnings.push("Could not locate the reaction interaction control inside the LinkedIn post.");return [];}await clickControl(page,c,"Reaction interaction");const seen=new Set<string>();const out:ScrapedEngagement[]=[];for(let r=0;r<50&&out.length<max;r++){const s=await reactionSurfaceAfterClick(page);if(!s){if(r===0)console.log("Reaction surface not detected after click; no page-wide profile fallback will be used.");break;}const a=s.locator('a[href*="/in/"],a[data-profile-url],a[data-test-profile-url]');const n=Math.min(await a.count().catch(()=>0),1000);for(let i=0;i<n&&out.length<max;i++){const x=a.nth(i);if(!(await x.isVisible().catch(()=>false)))continue;const href=profile((await x.getAttribute("href").catch(()=>""))||(await x.getAttribute("data-profile-url").catch(()=>""))||(await x.getAttribute("data-test-profile-url").catch(()=>""))||"");const name=clean((await x.textContent().catch(()=>""))||(await x.getAttribute("aria-label").catch(()=>"")));if(!href||!name||generic(name)||seen.has(href.toLowerCase()))continue;seen.add(href.toLowerCase());out.push({profileUrl:href,name,type:"REACTION",reactionType:"UNKNOWN"});}const before=clean(await s.innerText().catch(()=>""));await s.focus().catch(()=>{});await s.press("PageDown").catch(()=>{});await page.waitForTimeout(450);const after=clean(await s.innerText().catch(()=>""));if(after===before)break;}if(!out.length)warnings.push("Reaction list opened, but no public LinkedIn profile URLs were exposed inside the reaction surface.");console.log(`Reaction extraction: ${out.length} profile(s) captured.`);return out;}
export async function scrapePublicPost(postUrl:string,options:{maxComments?:number;maxReactions?:number}={}):Promise<ScrapeResult>{const maxComments=options.maxComments??500,maxReactions=options.maxReactions??500,warnings:string[]=[];const {browser,page}=await connect();try{await page.goto(postUrl,{waitUntil:"domcontentloaded",timeout:30000});await page.waitForTimeout(2000);const signedOut=await page.locator('input[name="session_key"],form[action*="login"]').count().catch(()=>0);console.log(`LinkedIn session: ${signedOut?"SIGNED OUT":"SIGNED IN"}`);if(signedOut)warnings.push("LinkedIn appears to be signed out in the connected Chrome profile.");const comments=await extractComments(page,maxComments,postUrl);const reactions=await extractReactions(page,maxReactions,postUrl,warnings);const merged=new Map<string,ScrapedEngagement>();for(const item of [...reactions,...comments]){const key=normalizeLinkedInUrl(item.profileUrl).toLowerCase();if(!key)continue;const old=merged.get(key);if(!old||item.type==="COMMENT")merged.set(key,item);}console.log(`Engagement merge: comments=${comments.length}, reactions=${reactions.length}, unique=${merged.size}.`);return{engagements:[...merged.values()],warnings};}finally{await page.close().catch(()=>{});await browser.close().catch(()=>{});}}
